repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.8.1"
    hooks:
      - id: prettier
        args: [--prose-wrap=always]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff-check
        args: [--fix, "--show-fixes"]
      - id: ruff-format
